quarkiverse/quarkus-quinoa

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
integration-tests/src/main/resources/application.properties

Fixes #26 
The default is now:
```properties
quarkus.quinoa.ui-dir=src/main/webui
```
The path is now relative to the project root as stated in the doc.

Switch to webui dir

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/resources/application.properties
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java

Before this in proxy dev-mode, META-INF/resources had priority over Quinoa and not in prod mode. 
This PR:
- Proxy dev-mode and prod mode behave the same,  META-INF/resources has priority over Quinoa.
- Introduce `quarkus.quinoa.ignored-path-prefixes` (Fixes https://github.com/quarkiverse/quarkus-quinoa/issues/62)
ping @sberyozkin @geoand @maxandersen

Make routing more consistent

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java

Replace all the '\' in relative path to '/' on Windows.
Fixes #100

Fix relative path mismatch on Windows when running in production mode

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/PackageManager.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaFrozenLockfileConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerManualYarnConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNPMConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNpmConfigBinaryOnWindowsTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerPNPMConfigBinaryOnWindowsTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerPNPMConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerYarnConfigBinaryOnWindowsTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerYarnConfigBinaryTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerYarnConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/devmode/ClassicDevModeTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/devmode/ForwardedDevModeTest.java
deployment/src/test/resources/application-forwarded.properties
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/resources/application.properties
runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/resources/application.yml

- Introduce `quarkus.quinoa.dev-server.check-path`: see doc.
- Rename `quarkus.quinoa.dev-server-port` to `quarkus.quinoa.dev-server.port`
- Rename `quarkus.quinoa.enable-dev-server-logs` to `quarkus.quinoa.dev-server.logs`
- Rename `quarkus.quinoa.dev-server-timeout` to `quarkus.quinoa.dev-server.check-timeout`
- Rename `quarkus.quinoa.always-install` to `quarkus.quinoa.force-install`

Clean config names & introduce "quarkus.quinoa.dev-server.*" 

---

deployment/src/test/java/io/quarkiverse/quinoa/test/devmode/ForwardedDevModeTest.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java

Fix non-Get request in proxy dev-mode

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/test/webui/package-lock.json

As this is `quarkus.quinoa.dev-server` is true by default, it won't change the current behavior (the `quarkus.quinoa.dev-server.port` is controlling whether it's enabled or not). 
This config allow to change the dev-server mode (external or quarkus) directly from the command for a one time run (e.g. when dev server is enabled in the config):
```console
quarkus dev -Dquarkus.quinoa.dev-server=false
```

Add config to enable/disable dev server

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java

Related to #215 
Now the root project dir can be detected if one of those exists:
- src/main
- config/application.properties
- config/application.yml
- config/application.yaml
Thanks to this, projects without a `src` dir, but instead a `webui` and a `config/application.properties` can work out of the box.

Quinoa can work without a src dir

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/resources/application.properties
integration-tests/src/main/ui-angular/package.json
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Fix #268 Netx JS support
Fix #71 Handle websockets in Dev Mode

Fix #268/#71: HMR support for web sockets

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevServerBuildItem.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

- Introduce `quarkus.quinoa.dev-server.host` which is optional and allow to configure the host for the dev-server.
- By default the host will be resolved from the host contained in the request headers (before it was using `localAddress.host()` which might be causing the ipv6 problem on some system)
Fixes #266

Fix host ipv6

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java

There is a bug in maven-frontend-plugin install throwing a DirectoryNotFoundException because the tmp directory is used (or something) when it's deleted. This catches the exception and warn instead of fail.

Fix node install in some edge cases

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java

Fix #355: Prevent NPE when UIDir is misconfigured

Fix #355: Prevent NPE when UIDir is misconfigured

---

runtime/src/main/resources/META-INF/quarkus-extension.yaml

Its been a couple of years I think its safe to remove the Preview label.

Change "preview" to "stable"

---

.github/workflows/build.yml

check maven version before build

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
docs/modules/ROOT/pages/index.adoc

Realized we support Vite for Vue3 Create Vue but legacy Vue CLI Service was not supported out of the box.

Add Vue legacy support

---

docs/modules/ROOT/assets/images/plus-sign.svg

This makes the + sign on the ReadME look better in both light and dark theme

Plus sign look better in dark/light theme

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
docs/modules/ROOT/pages/index.adoc

Solid Start support

---

runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java

remove wrapper in log

---

README.md

Adding a link to the high-level diagrams including module, library dependency and others (https://sourcespy.com/github/quarkiversequarkusquinoa/).
Built directly from source and updated on schedule. Intended to simplify developer's introduction to the project.
In the spirit of transparency - I am the author of the diagrams. Hope contributors find it useful.
Documentation-only change

Update README.md - add a link to repository map

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/devui/QuinoaDevUIProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/ConfiguredQuinoaBuildItem.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/InstalledPackageManagerBuildItem.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

- Trying to prevent this: https://github.com/eirslett/frontend-maven-plugin/issues/882
- This PR also split configuration and install buildsteps trying to fix #503 (without success but better split IMO)

Add Node.js install retry (5)

---

README.md

This PR attempts to fix the link to configure Quinoa to install nodejs. Based on the original link, this is my best guest. If it is not the correct address then consider this a roundabout way of raising the issue ^^

Fix 404 to Quinoa package manager

---

docs/modules/ROOT/pages/advanced-guides.adoc
docs/modules/ROOT/pages/main-concepts.adoc

I've noticed that a lot of the internal documentation links are broken. 
According to the [AsciiDoc documentation](https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/) we are supposed to use `xref:` instead of `link:` for this kinds of links.

Use xref instead of link for internal documentation links

---

docs/modules/ROOT/pages/web-frameworks.adoc

It is possible to use SvelteKit in SPA mode with Quarkus even in Dev Mode.
As SvelteKit does not have an index.html file during development, we need to configure Quinoa to point just to the Root URL when requesting the the entry point. 
But, as it produces that file for production, we also mark that configuration to apply only in dev mode with the `%dev.` prefix. 
Additionally, as SvelteKit uses SPA routing, we also need to enable it.
Fix #547

Update SvelteKit Documentation to support dev mode

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java

@ia3andy this broke vite in my local testing it causes those `/@` values to throw error in the browser of "invalid mime type" so if I remove this vite goes back to working.

Revert Vite ignore of /@

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
docs/modules/ROOT/pages/web-frameworks.adoc

check-https://nextjs.org/docs/pages/building-your-application/deploying/static-exports#version-history
Fix #580

NextJS 14 `next export` has been removed

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/FrameworkConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerCommandConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java

Currently dev mode will restart the dev service every time, significantly increasing hot reload time.
Currently the config does not implement equals, so the equals check is based on object equality and will always result in a restart of the dev service.

Fix dev service restart condition

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/DevServerConfigDelegate.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
integration-tests/src/main/resources/application.properties
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaRootPathTest.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/TestProfiles.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaHandlerConfig.java

Fixes https://github.com/quarkiverse/quarkus-quinoa/issues/574
Add a new config for this `quarkus.quinoa.dev-server.direct-forwarding` (when true, it forwards without the content-type-check)

Smart bypass of the dev server SPA

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaHandlerConfig.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java

Fixes #603 
This is a big issue which could affect production on different kind of apps (not only with Next), it should be backported.
**To mitigate this issue:**
- if not set (Optional), the dev server index page name is not used, only Next framework automatically overrides it (leading to the production startup failing). 
- If set (this is a new and not very commonly used config) , then currently the dev server index page name would be used in production leading to either a startup failing or a 404 on the index page

[Critical] Make sure the devServer indexPage is only used in dev mode

---

deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/PackageManagerInstallFactory.java
deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallAuthConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

Implementation of basic authentication using new config properties.
quarkus.quinoa.package-manager-install.basic-auth.username
quarkus.quinoa.package-manager-install.basic-auth.password
This solution can currently only authenticate with the same credentials for all download URLs.
Closes #614

Create new config for authentication in VertxFileDownloader

---

docs/modules/ROOT/pages/web-frameworks.adoc

I ran into a weird behavior while developing a SvelteKit frontend with Quinoa 
Whenever a full reload happend an a nested route, it would give me a 404 error. But if I followed a link to that same route it worked just fine. 
Then I tried it without Quinoa proxying the request, and there the full reload also worked perfectly fine. 
It turns out that SvelteKit will assume that its base directory is whatever the current path's parent directory is if the request is proxied to it the way that Quiona does it. 
By configuring it to not assume that it should be using relative paths by default, the problem was resolved.
Document how to configure SvelteKit to use absolute paths in its routing.

SvelteKit: Document relative paths configuration

---

integration-tests/src/main/resources/application.properties

The QuarkusIntegrationTest uses React, this makes sure it is the default ui-dir for the native test.

Fix ecosystem-ci

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/SslUtil.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/DevServerConfigDelegate.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerRunner.java

Fix #682: Allow to define if dev-server is HTTPS / TLS
This PR add support for HTTPS/TLS for dev-server.
It's my first PR on quarkus and quinoa so if I missed some standard/convention and need rework, tell me (or do the change).
Thanks.

Fix #682: Allow to define if dev-server is HTTPS / TLS

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/ForwardedDevServerBuildItem.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Added tls support to the real forwarder
#682 
- [] All new and existing tests passed. <== *Don't know how to launch them*

Fix #682: Allow to define if dev-server is HTTPS / TLS (Again)

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/ForwardedDevServerBuildItem.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerRunner.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaNetworkConfiguration.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

@ylemoigne @ia3andy 
Refactored the code as we were passing around `tls, insecure, host, port, websocket` everywhere making method signatures verbose.
This just moves that into a POJO we can pass around

Refactor TLS and network handling

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/ForwardedDevServerBuildItem.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Backport Fix #682: 2.3.x Allow to define if dev-server is HTTPS / TLS

Fix #682: 2.3.x Allow to define if dev-server is HTTPS / TLS

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/QuinoaConfigDelegate.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaAbsoluteUIDirTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaDefaultConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigRelativeRootPathTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigRootPathTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigUiRootPathTest.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
integration-tests/src/main/resources/application.properties
integration-tests/src/main/ui-lit/src/simple-greeting.js
integration-tests/src/main/ui-lit/webpack.config.js
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUiRootPathTest.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/TestProfiles.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java

This is a back-port of #691 to the `2.3.x` branch.
Note that if the `quarkus.quinoa.ui-root-path=/foo` is set, then `http://localhost:8080/foo` redirects to `http://localhost:8080/foo/` to serve the `index.html` file in production mode.
This happens, because in production mode `io.vertx.ext.web.handler.StaticHandler` is used to serve files which already implements this behavior.
Fixes #302

[2.3.x] Add root path for Quinoa Web UI

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/QuinoaConfigDelegate.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigRelativeRootPathTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigRootPathTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPathPrefixesRESTConfigUiRootPathTest.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
integration-tests/src/main/resources/application.properties
integration-tests/src/main/ui-lit/src/simple-greeting.js
integration-tests/src/main/ui-lit/webpack.config.js
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUiRootPathTest.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/TestProfiles.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java

This change adds the following new property: `quarkus.quinoa.ui-root-path`
This is the path where the Web UI will be hosted and is always relative to `quarkus.http.root-path`.
The default value is `/`, which is a non-breaking change.
For example setting the property `quarkus.quinoa.ui-root-path=/ui` would serve the Web UI at the path `/ui`.
The paths in the property `quarkus.quinoa.ignored-path-prefixes` are relative to `quarkus.quinoa.ui-root-path` which is a non-braking change because the default of `quarkus.quinoa.ui-root-path` is `/`.
I added normalization to the ignored paths, so paths like `foo///bar` would now be added as `/foo/bar` and this should be good since ignored paths are checked against the normalized request path from vertx.
When the property is not set then the automatic …

Add root path for Quinoa Web UI

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFramework.java
integration-tests/src/main/ui-angular-esbuild/package-lock.json
integration-tests/src/main/ui-angular-esbuild/package.json

I have changed the detection of angular configuration application. Before we used the package.json's name. Now we get the application available in angular.json file. If multiple applications exist in this configuration, an exception will be thrown. Users have to help quinoa to know which one must be build in this context.
closes #721 
Fix #723

[Fix/727] Change location for get angular application configuration

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerCommandConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/PackageManagerCommandConfigDelegate.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/delegate/QuinoaConfigDelegate.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/items/PublishedPackageBuildItem.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerRunner.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/types/ConfiguredPackageManager.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/types/PackageManager.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerPublishTest.java
deployment/src/test/webui/package.json
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

Additional build step has been introduced to run package manager publish command. This allows to push built package to the remote registry. This is particularly handy when using together with `quarkus.quinoa.just-build` option enabled.
PR is a follow-up of the discussion here
https://github.com/quarkiverse/quarkus-quinoa/discussions/756

Publish built package

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java

This PR adds a check to ensure that if `package.json` doesn't contain an `output` field, we don't get a null pointer exception, but instead, get an appropriate warning.
Error in question:
```
[error]: Build step io.quarkiverse.quinoa.deployment.QuinoaProcessor#prepareQuinoaDirectory threw an exception: java.lang.NullPointerException: Cannot invoke "jakarta.json.JsonString.getString()" because the return value of "org.eclipse.parsson.JsonObjectBuilderImpl$JsonObjectImpl.getJsonString(String)" is null
[ERROR] 	at org.eclipse.parsson.JsonObjectBuilderImpl$JsonObjectImpl.getString(JsonObjectBuilderImpl.java:249)
[ERROR] 	at io.quarkiverse.quinoa.deployment.framework.override.NextFramework.override(NextFramework.java:34)
[ERROR] 	at io.quarkiverse.quinoa.deployment.framework.FrameworkType.overr …
```

fix: added check to check if package.json contains output

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
docs/modules/ROOT/pages/web-frameworks.adoc

This PR adds a section to the web frameworks documentation about Next.js not being fully supported for versions 13 and above. It also adds a warning message when using Next.js.

docs: added caution section for nextjs and warning

---

docs/modules/ROOT/pages/index.adoc

When generating a new application,
```properties
quarkus.quinoa.ui-root-path=quinoa
```
is used and there is no `quinoa.html`
in the generated application.

Fix quickstart instructions

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFramework.java
deployment/src/test/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFrameworkTest.java
deployment/src/test/resources/frameworks/angular/builder-application-output-obj-browser.json
deployment/src/test/resources/frameworks/angular/builder-application-output-obj-no-browser.json
deployment/src/test/resources/frameworks/angular/builder-application-output-str.json
deployment/src/test/resources/frameworks/angular/builder-browser-output-str.json

Since `outputPath` in `build` section of `angular.json` can be either [a String or an Object](https://angular.dev/reference/configs/workspace-config#output-path-configuration), existing `AngularFramework` was failing in the latter case.
Fixed that. Test cases cover all _schema-valid_ variants of `build` section of `angular.json`.

buildDir calculation also supports outputPath being a JsonObject

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFramework.java
deployment/src/test/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFrameworkTest.java

Updated build directory resolution logic to support the default output path detection introduced in Angular CLI v20.
Fix https://github.com/quarkiverse/quarkus-quinoa/issues/892

Support Angular CLI v20 default output path detection
