quarkiverse/quarkus-quinoa

.github/project.yml
README.md
deployment/pom.xml
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
docs/pom.xml
integration-tests/pom.xml
pom.xml
runtime/pom.xml
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Add a temporary fix for the too many default route error

---

integration-tests/pom.xml
integration-tests/src/main/java/io/quarkiverse/quinoa/it/QuinoaResource.java
integration-tests/src/main/ui-lit/src/simple-greeting.js
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUILitTest.java

this test ow include testing that the componet loads on the page, and the component fetch data from the api
Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

Added better integration test for lit component

---

README.md
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/ui-react/src/App.js
integration-tests/src/test/java/io/quarkiverse/quinoa/it/PlaywrightManager.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaTestProfiles.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUIAngularTest.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUILitTest.java
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUITest.java

@phillip-kruger it would be nice to make the `PlayrightManager` available to devs. I am not sure how we could do that as it's a test dependency.

Introduce PlayrightManager and use it in all UI tests

---

docs/antora.yml

As in https://quarkiverse.github.io/quarkiverse-docs/quarkus-quinoa/dev/index.html

Fixed documentation title

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/PackageManager.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

- make dev server timeout configurable
- use 30000ms as default

Make dev server timeout configurable

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java

Add native support

---

.github/project.yml

Release 1.0.0-CR1

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java

Fixes #30 
```properties
quarkus.quinoa.enable-spa-routing=true
```
cc @tqvarnst I think you wanted that one :)

Enable SPA routing

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java

Signed-off-by: Radim Vansa <rvansa@redhat.com>

Quinoa dev server should not be restarted with Quarkus live-reload #52

---

runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java

Forward query in dev-mode

---

docs/modules/ROOT/pages/index.adoc

Improve doc about build dir

---

.github/project.yml

- https://github.com/quarkiverse/quarkus-quinoa/pull/131
- https://github.com/quarkiverse/quarkus-quinoa/pull/129
- https://github.com/quarkiverse/quarkus-quinoa/pull/127

Release 1.1.1

---

integration-tests/src/main/resources/application.properties
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaUIAngularTest.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Fix route order for 2.11.x

---

runtime/src/main/resources/META-INF/quarkus-extension.yaml

Promote to preview

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/EffectiveCommands.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallPrependBinaryTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java

Fix PATH when using package-manager-install

---

docs/modules/ROOT/pages/index.adoc

Added example for how to get Vite and Quinoa to work together.

add Vite-howto to documentation

---

integration-tests/src/main/resources/application.properties
integration-tests/src/test/java/io/quarkiverse/quinoa/it/QuinoaRootPathTest.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaSPARoutingHandler.java

Fix routing when root-path is set  in SPA mode

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java

Improve stopDev robustness when the dev server is stuck

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaNoDirTest.java

Improve error messages when the Web UI dir is not found

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/DevServerConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevWebSocketProxyHandler.java

This is simpler and it can be customized anyway in case of need.

Stop computing host for dev-server

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/devui/QuinoaDevUIProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstallConfig.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc
runtime/src/main/java/io/quarkiverse/quinoa/devui/QuinoaJsonRpcService.java

Fix #174/#175: Support for PNPM and YARN installers

---

.github/workflows/build.yml

Bump Actions to v3

---

CODE_OF_CONDUCT.md

add a CODE_OF_CONDUCT.md for community guidelines

add: CODE_OF_CONDUCT.md

---

runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/webui/package.json

Upgrade Webpack devDependencies

Upgrade Webpack

---

runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/webui/package-lock.json

upgrade webpack codestart devDependencies

upgrade webpack codestart devDependencies

---

integration-tests/src/main/ui-react/package-lock.json
integration-tests/src/main/ui-react/package.json

upgrade react-dom from 17.x to 18.x

integration-test: upgrade react-dom

---

deployment-testing/src/main/java/io/quarkiverse/quinoa/deployment/testing/QuinoaQuarkusUnitTest.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java

Based on how Quarkus checks for Windows in other Extensions.

Refactor IS_WINDOWS check

---

pom.xml

bump maven compiler-plugin

---

README.md

I used a dash instead of undscore.  Whoops!

Fix Node Logo Link

---

README.md

Center: logo and heading in README.md

Center: logo and heading

---

.github/workflows/welcome.yml

add: Welcome workflow

---

README.md

add: resource link

---

README.md

Add issue badge in README.md

---

runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/resources/application.yml

let quinoa download node 18.16.0

let quinoa download node 18.16.0

---

integration-tests/src/main/resources/application.properties

upgrade: node version for angular package manager

---

runtime/src/main/resources/META-INF/quarkus-extension.yaml

1.x: preview to stable

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java

Fix #370: DevServices UI updates

Fix #370: DevServices UI updates

---

runtime/src/main/resources/META-INF/quarkus-extension.yaml

Adds a logo to the documentation site: https://quarkus.io/extensions/

Add docs logo

---

.github/workflows/build.yml

avoid redownloading and reinstalling dependencies, result in faster build

avoid redownloading and reinstalling dependencies

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaDirectoryBuildItem.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/devui/QuinoaDevUIProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/DetectedFramework.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/EffectiveCommands.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManager.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerCommands.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/index.adoc

PR to allow auto-detecting framework and then configuring for that framework if detected in package.json.
Fix #367: Framework automation detection
@ia3andy @holly-cummins  this is what I was thinking to start before adding the code to auto-detect and configure.  Let me know any thoughts before I continue...

Fix #367: Framework automation detection

---

docs/modules/ROOT/pages/index.adoc

@ia3andy I made a whole new `Frameworks` major section and cleaned up and removed some settings no longer needed.

Update docs for framework auto detection

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java

set node v18.16.0 to install by default

set node v18.16.0 to install by default

---

docs/modules/ROOT/pages/index.adoc

Docs update for node download

---

integration-tests/src/main/ui-lit/package-lock.json
integration-tests/src/main/ui-lit/package.json
integration-tests/src/main/ui-react/package-lock.json
integration-tests/src/main/ui-react/package.json
integration-tests/src/main/ui-vue/package.json
integration-tests/src/main/ui-vue/yarn.lock

upgrade dependencies for react, vue and lit

---

integration-tests/src/main/ui-vue/package.json

fix npm run script for vue

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java
integration-tests/src/main/resources/application.properties

let quinoa download node v18.16.1

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/index.adoc

Fix #394: Astro support

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/index.adoc

Fix #391: Update ignored dirs and Svelte instructions

Fix #391: Update ignored dirs and Svelte instructions

---

runtime/src/main/java/io/quarkiverse/quinoa/QuinoaHandlerConfig.java

replace QuinoaHandlerConfig by an empty string when it is configured to "/"
Closes #391 
- [x ] My code follows the code style of this project.
- [x ] All new and existing tests passed.

make indexPage value to empty string when configured with value "/"

---

docs/modules/ROOT/pages/index.adoc

Update quinoa docs

---

docs/modules/ROOT/pages/index.adoc

Update node version in docs

---

docs/modules/ROOT/pages/includes/attributes.adoc

Update quinoa version

---

runtime/src/main/resources/META-INF/quarkus-extension.yaml

add new framework keywords for quarkus-extension.yml

add new framework keywords for quarkus-extension

---

docs/modules/ROOT/pages/index.adoc

Add resource of frameworks in docs

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

https://guides.emberjs.com/release/getting-started/quick-start/

Ember.js Support

---

.github/project.yml

2.0.7 Release

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

Aurelia support

---

runtime/pom.xml

As recommended by @gastaldi 
See: https://groups.google.com/g/quarkus-dev/c/8Y4ocD2BxXI

GraalVM SDK

---

.github/project.yml

Reverts quarkiverse/quarkus-quinoa#428

Revert "2.0.7 Release"

---

runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/resources/application.yml

let's keep current node v18.16.1

---

README.md

@gastaldi as said, https://github.com/orgs/quarkiverse/discussions/122

Change Quinoa docs URL

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

POLYMER Support

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

qwik support

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

Gatsby support

---

docs/modules/ROOT/pages/index.adoc

add docs for new frameworks

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java
docs/modules/ROOT/pages/index.adoc

Support Nuxt

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

Cycle.js Support

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/resources/application.properties
runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/resources/application.yml

Let's quinoa download current node v18.17.0

---

integration-tests/src/main/ui-vue/package.json
integration-tests/src/main/ui-vue/yarn.lock

let's catch better common problem

---

integration-tests/src/main/java/io/quarkiverse/quinoa/it/QuinoaResource.java

Add new rest service

---

pom.xml

Add project description

---

pom.xml

Add issue management

---

integration-tests/src/main/ui-lit/package-lock.json
integration-tests/src/main/ui-lit/package.json

webpack update

---

.gitattributes

Enforce normalization of line ending to LF

Added .gitattributes to repo

---

pom.xml

[#470] Developer profile

---

docs/modules/ROOT/pages/includes/attributes.adoc

Update  Quinoa 2.0.8

---

.github/workflows/build.yml

use letest pnpm v8.6.12

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

Refine Support

---

docs/modules/ROOT/pages/index.adoc

document refine

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallPrependBinaryTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNPMOverrideBuildEnvTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerNPMOverrideEnvTest.java

devolup -> develope

---

integration-tests/src/main/ui-angular/package-lock.json
integration-tests/src/main/ui-vue/yarn.lock

fix: Dependabot vulnerabilities alerts. I got 3 mail for this.

fix: Dependabot vulnerabilities alerts

---

integration-tests/src/main/ui-angular/package-lock.json
integration-tests/src/main/ui-vue/yarn.lock

Reverts quarkiverse/quarkus-quinoa#480

Revert "fix: Dependabot vulnerabilities alerts"

---

.github/workflows/build.yml
.github/workflows/quarkus-snapshot.yaml
.github/workflows/release.yml

use action/checkout@v4

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/FrameworkType.java

Fix #500: Framework INFO to TRACE messages

Fix #500: Framework INFO to TRACE messages

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/ForwardedDevProcessor.java
docs/modules/ROOT/pages/includes/attributes.adoc
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

The host was wrong after a restart (using vite for example)

Fix wrong host after restart

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java
docs/modules/ROOT/pages/index.adoc
integration-tests/src/main/resources/application.properties
runtime/src/main/codestarts/quarkus/quinoa-codestart/base/src/main/resources/application.yml

download node 18.18.0 LTS

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
docs/modules/ROOT/pages/includes/attributes.adoc

Fix #516: Better error message if failed moving files

Fix #516: Better error message if failed moving files

---

.github/project.yml
integration-tests/src/main/ui-vue/yarn.lock

@melloware go?
@fblan did you give it a try?

Release 2.2.0

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/devui/QuinoaDevUIProcessor.java

Fix #538: DevUI check for optional config

Fix #538: DevUI check for optional config

---

docs/modules/ROOT/pages/web-frameworks.adoc

While reading the Svelte configuration documentation, I saw this easy to fix error and wanted to fix it.

docs: spelling mistake chnages -> changes in Svelte configuration documentation

---

docs/modules/ROOT/pages/advanced-guides.adoc

Docs: Define npm install by quinoa

---

docs/modules/ROOT/pages/config-reference.adoc

Docs heading for Config Reference is not align properly.

Docs: heading for Config Reference align properly

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallCommandOverrideTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java
docs/modules/ROOT/pages/advanced-guides.adoc
integration-tests/src/main/resources/application.properties

Node: let quinoa use new LTS version 20.9.0

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/QuinoaConfig.java
docs/modules/ROOT/pages/advanced-guides.adoc

Vite support in Dev Mode

---

.github/workflows/build.yml
.github/workflows/quarkus-snapshot.yaml
.github/workflows/release.yml

Depreciated: java github actions

Depreciated: java github actions

---

deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallCommandOverrideTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallTest.java
deployment/src/test/java/io/quarkiverse/quinoa/test/QuinoaPackageManagerInstallWithSpaceTest.java
docs/modules/ROOT/pages/advanced-guides.adoc
docs/modules/ROOT/pages/index.adoc

Let quinoa download latest LTS node version

Let quinoa download node 20.x

---

pom.xml
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaRecorder.java

Fix #595 2.2.x backports for LTS

2.2.x backports for LTS

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaUIResourceHandler.java

Not a fix for the issue just a better error than the weird Vert.X missing index 0 error we were getting

Better error for missing static index page

---

deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/PackageManagerInstallFactory.java
deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallAuthConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/config/PackageManagerInstallConfig.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
docs/modules/ROOT/pages/includes/quarkus-quinoa.adoc

2.2.x Create new config for authentication in VertxFileDownloader

2.2.x Create new config for authentication in VertxFileDownloader

---

.github/project.yml

2.3.3 Release

---

.github/project.yml

2.2.4 Release

---

.github/project.yml

2.3.4 Release

---

.github/project.yml

2.2.5 Release

---

docs/modules/ROOT/pages/web-frameworks.adoc

Docs: Vite Configuration With Quinoa

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java
docs/modules/ROOT/pages/advanced-guides.adoc

Fix #631: OpenAPI code generation docs

Fix #631: OpenAPI code generation docs

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java

Fix #648: Files.walk allow FOLLOW_LINKS

Fix #648: Files.walk allow FOLLOW_LINKS

---

.github/project.yml

Release 2.3.5

---

.github/project.yml

2.3.6 Release

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
runtime/src/main/java/io/quarkiverse/quinoa/QuinoaDevProxyHandler.java

Fix static imports

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java

Fix #705: Solid Start use vinxi dev also

Fix #705: Solid Start use vinxi dev also

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java

Fix #707: Add Farm support

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerRunner.java

Currently, Quinoa generates a lot of logs during
quarkus dev because it has to do a bunch of stuff. Most of these logs are only useful as progress
markers or when an error occurs , so they are
great candidates for the `StartupLogCompressor`

Quite down Quinoa logs

---

docs/modules/ROOT/pages/web-frameworks.adoc

Fix #591: Add Svelte Dynamic route in docs

Fix #591: Add Svelte Dynamic route in docs

---

README.md
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/web-frameworks.adoc

Update the link to angular to the new angular website angular.dev

Update angular url to the new angular website

---

integration-tests/src/main/resources/application.properties

Fix #755: Rename resteast-reactive to rest

Fix #755: Rename resteasy-reactive to rest

---

deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java

Fix #766: ProxyOptions for Vert.X Downloader

Fix #766: ProxyOptions for Vert.X Downloader

---

deployment/src/main/java/com/github/eirslett/maven/plugins/frontend/lib/VertxFileDownloader.java
pom.xml

Fix #683: FrontEnd 1.15.1

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/QuinoaProcessor.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkConfigOverrideFactory.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/FrameworkType.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/AngularFramework.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/GenericFramework.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/NextFramework.java
deployment/src/main/java/io/quarkiverse/quinoa/deployment/framework/override/ReactFramework.java

Changed the code that looks up the angular.json so that it uses the absolute "ui dir" path (which is based on the project directory) instead of basing the path off the working directory.
Fix #812

Fix path resolution for angular.json

---

.github/workflows/hooks/pre-prepare-release.sh
.github/workflows/quarkus-snapshot.yaml

- **Change to v1**
- **Install pnpm**

Install pnpm during prepare release

---

.github/workflows/release-prepare.yml

That allows you to retry on failed releases

Adding `workflow_dispatch` in release-prepare.yml

---

docs/modules/ROOT/pages/web-frameworks.adoc

Added Nuxt configuration section around circumventing dynamic routes breaking.
Closes #825

Added Nuxt configuration section to documentation

---

.idea/icon.svg

Fix #810: Gradle needs empty /src/main/java

Fix #810: Gradle needs empty /src/main/java

---

integration-tests/src/main/resources/application.properties
integration-tests/src/main/ui-angular-esbuild/package-lock.json
integration-tests/src/main/ui-angular-esbuild/package.json
integration-tests/src/main/ui-angular-esbuild/src/app/app.component.ts

Updates Angular used in `ui-angular-esbuild` of `integration-tests` to 19.2.x in order to be compatible with vite update from 5.3.2 to 6.0.11 (see  #829 )

upgrade Angular to v19

---

deployment/src/main/java/io/quarkiverse/quinoa/deployment/packagemanager/PackageManagerInstall.java

Fix #851: Remove Corepack
